### PR TITLE
Added notification and html file download.

### PR DESCRIPTION
**Pull request by sudarpo**
Some enhancements for this wonderful extension:
- Added notification to show parsing is completed and ready to download
- Change file download to html file

Thanks a lot for your initial work.

### CODE REVIEW

**Comment by erfansahaf** [comment]
@sudarpo Good enhancement! But just one thing:

I use the downloaded text file to import download links into my Download Manager (Perspolice / IDM) and it does not support HTML files. It would be good to download both `txt` and `html` files for such a purpose.

**Comment by sudarpo** [comment]
@erfansahaf, noted on your use case with Download Manager. Perhaps we can add options to download text or html. Let me update them shortly.

**Comment by erfansahaf** [comment]
@sudarpo Thank you for the updates.

I'm facing a strange behavior in clicking any of these buttons. When I click once on any of the two, nothing happens. But when I keep doing that multiple times, finally a file gets downloaded.

**Comment by sudarpo** [comment]
That's weird. I cant reproduce that behavior. It's working fine with Chrome in Mac and Windows. 

Did you see "Parsing completed. Total videos: ##" message? 

Can you try to uncomment this line and see you get any message in console.
`// console.log("onMessage", request, "sender", sender);`

**Comment by erfansahaf** [comment]
I'm running the extension on Ubuntu with Chrome Version 70.0.3538.77 (Official Build) (64-bit).

I can see the "Parsing Complete" message on the Top Right corner and also the console. I did the uncomment thing but it seems the Listener does not run at all cuz no `onMessage` gets printed in the console. Like I mentioned before, after multiple tries when the file gets downloaded, the `onMessage` will be logged in the console.

I also tested the extension on a fresh Chrome profile with no other extension installed to check is there any interference or not. The result was the same with no difference.

**Comment by sudarpo** [comment]
Just checking if you have updated manifest.json ?

Chrome version 70.x.. isn't latest version now is 85.x. ? 😧 
You have specific requirement to use version 70 ?

**Comment by erfansahaf** [comment]
Yes, I have the most recent manifest.json with version `0.2`.

I don't have any specification requirements, the chrome has not updated itself. I'm not experienced in developing Chrome extensions but have you used any feature that is not supported on version 70?

**Comment by sudarpo** [comment]
I am not sure, @erfansahaf .. I'm not experienced extension developer too :)

I just tested in Ubuntu with Google Chrome 85, it works fine. So it's the browser version. 
My bet is the tabs runtime that breaks in v70.

**Comment by erfansahaf** [comment]
I updated my chrome version to the latest version. The previous problem solved but a new one occurred!

I'm allowed to download one file type (`txt` or `html`) in each page load. If I try to download both types, only the first on will be downloaded.

I think it's relevant to the previous problem. Can you reproduce this one?

**Comment by sudarpo** [comment]
I cant reproduce the issue mentioned.

In my testing:

- Load a course
- Get parse completed alert
- Click extension icon, and choose to download text - it will download text file
- In the same page load, click extension icon, and choose to download html - it will download html file
- And i can click multiple times to download both files

**Comment by erfansahaf** [comment]
The problem is something called `Multiplefile Download Permission`. When it is not granted by user, only the first one will be downloaded. I think it should be mentioned in the readme so others will be aware of.

It would be nice if you add related description to this PR in README for better documentation. Then we can go on and merge this!

**Comment by sudarpo** [comment]
Great that you resolved that issue @erfansahaf 

I forgot about the download prompt. Added more notes in Readme. Feel free to amend it. Thanks.

**Comment by erfansahaf** [comment]
Very well, it's time to merge the PR. Thank you for your contribution.

**Pull request merged**
