### PR TITLE
Fix bug, HTML changes and add new download option

### PR DESCRIPTION
**Pull request by plistiak**
Hi.
I fixed extension to work after latest KodiKloud webpage changes. Now it works also on main course page and it is not necessary to click on any lecture. But still works also on lecture page, of course. There are also small bug fixes and I add two new option - log to console (just for debugging purpose) and download as script.

Peter L.

### CODE REVIEW

**Comment by erfansahaf** [comment]
Hey there!

Thanks for sending this PR. I have pulled your changes and loaded the extension but sadly, it's not working. 
That message that shows the extension has parsed web page doesn't show up and the download buttons are not working either.

**Comment by plistiak** [comment]
I'm sorry, I don't know what happen. I will check it, but now I have no access to any computer.

**Comment by jaskeerat789** [comment]
Kodekloud recently updated their entire UI, so that may be the reason.
 their old website is available at [legacy.kodekloud.com](legacy.kodekloud.com)

**Comment by plistiak** [comment]
Hi guys. I'm sorry, I have checked new kodekloud.com website. It looks that it is not possible to get addresses of all videos for the course by parsing single webpage. My opinion is to take links to all chapters, download them via Fetch API and parse video url from each. But, to be honest, I don't have time for this and I also cancel my subscription at KodeKloud. But as I saw, they host videos on Vimeo, so extensions for dowloading vimeo could help.

**Comment by erfansahaf** [comment]
@plistiak Ok then. Thanks for your contribution. 

I will work on it when I find some free time.

**Pull request closed without merging**
